export const verdad = [
  "¿Alguna vez has mentido a un amigo cercano?",
  "¿Cuál es el secreto más grande que has guardado de tus padres?",
  "¿Qué es lo más embarazoso que te ha pasado en público?",
  "¿Alguna vez has hablado mal de un amigo a sus espaldas?",
  "¿Cuál es tu mayor inseguridad?",
  "¿Alguna vez te has sentido atraído/a por la pareja de un amigo?",
  "¿Cuál es la mayor cantidad de dinero que has gastado en algo estúpido?",
  "¿Has stalkeado a alguien en redes sociales recientemente?",
  "¿Qué es lo más extraño que haces cuando estás solo/a?",
  "¿Cuál ha sido tu peor cita?",
  "¿Cuál es la mentira más grande que has dicho en una entrevista de trabajo?",
  "¿Qué es lo más infantil que aún haces?",
  "¿Alguna vez has fingido estar enfermo para no ir al trabajo o a la escuela?",
  "¿Alguna vez has tenido un apodo ofensivo?",
  "¿Alguna vez has roto algo en casa de un amigo y no se lo dijiste?",
  "¿Cuál es el rumor más cruel que has escuchado sobre ti?",
  "¿Alguna vez has llorado por una película que en realidad no era triste?",
  "¿Has dicho alguna vez 'te amo' sin sentirlo realmente?",
  "¿Cuál es la peor mentira que has dicho para salir de una situación difícil?",
  "¿Cual ha sido la compra mas cara que has hecho?",
  "¿Te has quedado dormido en clases?",
  "¿Que es lo mas extraño que has encontrado debajo en el colegio/universidad o trabajo?",
  "¿Cuál ha sido tu mayor desafío en una relación?",
  "¿Cuál es el cumplido más extraño que has recibido?",
  "¿Cuál es el lugar más atrevido donde te gustaría ir de vacaciones?",
  "¿Alguna vez has tenido un flechazo instantáneo con alguien?",
  "¿Qué es lo más atrevido que has dicho a alguien que te gusta?",
  "¿Alguna vez has coqueteado con alguien solo por diversión?",
  "¿Qué es lo más inesperado que te ha pasado en una cita?",
  "¿Alguna vez has sentido celos por alguien que no era tu pareja?",
  "¿Cuál es la cosa más atrevida que has hecho en público?",
  "¿Alguna vez has hecho algo solo por impresionar a alguien?",
  "¿Cuál es el gesto romántico más loco que has hecho por alguien?",
  "¿Alguna vez has tenido un secreto que nunca le has contado a nadie?",
  "¿Qué es lo más atrevido que te gustaría probar en una cita?",
  "¿Alguna vez te has sentido atraído/a por alguien que no esperabas?",
  "¿Cuál es el piropo más atrevido que has recibido?",
  "¿Alguna vez has intentado impresionar a alguien y fallado estrepitosamente?",
  "¿Cuál es la cosa más inesperada que alguien ha hecho por ti en una cita?",
  "¿Alguna vez te has sentido incómodo/a con una broma picante?",
  "¿Qué es lo más atrevido que has hecho en un lugar público?",
  "¿Alguna vez has tenido una conversación que se puso más intensa de lo esperado?",
];

export const retos = [
  "Toma un trago sin usar las manos.",
  "Haz un fondo blanco de tu bebida.",
  "Deja que alguien elija una bebida fuerte para que la bebas.",
  "Bebe un vaso de agua en lugar de alcohol en tu próximo turno.",
  "Toma un shot de la bebida que elija el grupo.",
  "Bebe un trago cada vez que alguien diga 'verdad' en el próximo minuto.",
  "Deja que alguien te sirva un trago doble.",
  "Canta una canción mientras bebes un trago.",
  "Haz un brindis por alguien en la sala y luego bebe.",
  "Toma un shot cada vez que alguien mencione un color.",
  "Imita a un camarero y sirve bebidas a todos los demás.",
  "Haz una ronda de bebidas para todos los jugadores.",
  "Bebe de un vaso sin usar las manos.",
  "Toma un trago mientras haces un reto físico (como flexiones).",
  "Deja que alguien elija una bebida y toma un shot de ella.",
  "Bebe un trago de una bebida extraña mezclada por el grupo.",
  "Cambia tu bebida con la de alguien más y bebe.",
  "Bebe con los ojos vendados y adivina qué es.",
  "Haz un reto de equilibrio mientras bebes.",
  "Haz un fondo blanco mientras cantas una canción.",
  "Bebe un trago cada vez que alguien se ríe durante el próximo minuto.",
  "Toma un trago y luego cuenta un chiste.",
  "Deja que alguien elija tu próximo trago.",
  "Bebe un shot mientras haces un reto de baile.",
  "Cambia tu bebida con la de alguien más y bebe sin quejarte.",
  "Bebe un trago mientras haces 10 abdominales.",
  "Haz un fondo blanco de tu bebida mientras haces una confesión.",
  "Imita a un camarero borracho mientras sirves un trago.",
  "Bebe un trago mientras te tapas la nariz.",
  "Haz una ronda de shots para todos en la sala.",
  "Imita a otro jugador durante los próximos 2 turnos.",
  "Deja que alguien revise tu historial de búsqueda.",
  "Cuenta tu mayor secreto en voz alta.",
  "Publica una foto vergonzosa en tus redes sociales.",
  "Haz 10 flexiones mientras todos te miran.",
  "Llama a tus padres y diles que tienes una confesión importante.",
  "Deja que alguien elija una foto en tu teléfono y la envíe a cualquier persona.",
  "Haz una llamada de broma a alguien elegido por el grupo.",
  "Habla con acento extranjero durante los próximos 3 turnos.",
  "Imita el sonido de un animal elegido por el grupo durante 1 minuto.",
  "Cuenta una historia embarazosa de tu adolescencia.",
  "Baila una canción ridícula durante 1 minuto.",
  "Haz una selfie haciendo una cara ridícula y publícala en tus redes sociales.",
  "Deja que otro jugador envíe un mensaje a cualquier contacto en tu teléfono.",
  "Llama a un amigo y confiesa un amor platónico falso.",
  "Haz una videollamada a alguien y habla en un idioma inventado durante 1 minuto.",
  "Haz un dibujo en tu cara con un marcador lavable.",
  "Haz una publicación en redes sociales diciendo que tienes un secreto importante que revelar mañana.",
  "Pide perdón a un amigo por algo que nunca hiciste.",
  "Dile a alguien en la habitación lo que realmente piensas de él/ella.",
  "Haz un cumplido exagerado a alguien del grupo.",
  "Envía un mensaje de texto aleatorio a la última persona en tu lista de contactos.",
  "Deja que otro jugador elija el próximo estado de tu WhatsApp.",
  "Come una mezcla de alimentos elegida por los demás jugadores.",
  "Deja que alguien te dibuje en la cara con los ojos vendados.",
  "Publica una actualización de estado absurda en tus redes sociales.",
  "Llama a un amigo y finge que estás enojado/a sin razón.",
  "Dile a alguien en la sala algo que siempre has querido decirle pero nunca te atreviste.",
];
