export const yoNuncaNuncaFrases = [
  "Yo nunca nunca he mentido sobre mi edad.",
  "Yo nunca nunca he saltado clases.",
  "Yo nunca nunca he comido comida que se cayó al suelo.",
  "Yo nunca nunca he mentido sobre estar ocupado para evitar a alguien.",
  "Yo nunca nunca he llorado viendo una película.",
  "Yo nunca nunca he hecho trampa en un examen.",
  "Yo nunca nunca he enviado un mensaje al número equivocado.",
  "Yo nunca nunca he espiado el perfil de alguien en redes sociales.",
  "Yo nunca nunca he olvidado el nombre de alguien justo después de conocerlo.",
  "Yo nunca nunca he pedido dinero en un centro comercial.",
  "Yo nunca nunca he dejado de seguir a alguien en redes sociales por publicar demasiado.",
  "Yo nunca nunca he estado sin ducharme más de dos días.",
  "Yo nunca nunca he dejado de hablar a un amigo por una tontería.",
  "Yo nunca nunca he cantado en la ducha.",
  "Yo nunca nunca he olvidado un cumpleaños importante.",
  "Yo nunca nunca he usado una excusa falsa para salir de una cita.",
  "Yo nunca nunca he perdido algo y culpado a alguien más.",
  "Yo nunca nunca he fingido estar enfermo para no salir con amigos.",
  "Yo nunca nunca he robado nada en una tienda.",
  "Yo nunca nunca he tenido diarrea en casa de otra persona o en un sitio público.",
  "Yo nunca nunca he bebido antes de los 18 años.",
  "Yo nunca nunca he dejado un mensaje en visto.",
  "Yo nunca nunca he roto algo y culpado a otra persona.",
  "Yo nunca nunca he robado algo sin darme cuenta.",
  "Yo nunca nunca he estado celoso de un amigo.",
  "Yo nunca nunca he salido corriendo de una cita.",
  "Yo nunca nunca he fingido ser otra persona por teléfono.",
  "Yo nunca nunca he entrado a una casa o lugar prohibido sin permiso.",
  "Yo nunca nunca he olvidado la cartera en casa.",
  "Yo nunca nunca he dado un consejo que yo mismo no seguiría.",
  "Yo nunca Nunca he vomitado la casa de un amigo.",
  "Yo nunca Nunca me declare en público.",
  "Yo nunca Nunca le dije mamá a la profesora.",
  "Yo nunca Nunca me ilusione a la semana de hablar con alguien.",
  "Yo nunca Nunca me tire un gas en el salón.",
  "Yo nunca Nunca pelee en una fiesta.",
  "Yo nunca Nunca llegue con grajo al colegio.",
  "Yo nunca Nunca llore viendo un anime, seríe o película.",
];

export const penitenciasYoNunca = [
  "Toma un trago.",
  "Haz una llamada de broma a alguien que el grupo elija.",
  "Deja que otro jugador publique algo en tu red social.",
  "Baila una canción elegida por el grupo.",
  "Haz 10 flexiones o abdominales.",
  "Envía un mensaje vergonzoso a alguien que el grupo elija.",
  "Habla con un acento extranjero durante los próximos 3 turnos.",
  "Permite que alguien revise tu historial de búsqueda.",
  "Cuenta un secreto.",
  "Deja que alguien elija una foto en tu teléfono y la envíe a cualquier persona.",
  "Publica una historia embarazosa en tus redes sociales.",
  "Envía un mensaje de amor a alguien sin explicar el contexto.",
  "Haz una llamada a un restaurante y pregunta por el menú en un idioma inventado.",
  "Permite que otro jugador envíe un mensaje en tu nombre en un grupo de WhatsApp.",
  "Imita el sonido de un animal.",
  "Cuenta la historia más vergonzosa de tu vida.",
  "Deja que otro jugador envíe un mensaje a cualquier contacto en tu teléfono.",
  "Deja que el grupo elija un nuevo apodo para ti por el resto del juego.",
  "Permite que alguien te haga una pregunta incómoda y debes responder con la verdad.",
  "Haz una videollamada a alguien al azar y habla durante 30 segundos.",
  "Permite que alguien más responda un mensaje que recibas.",
  "Cambia tu foto de perfil a una imagen que elija el grupo.",
  "Haz 30 segundos de sentadillas.",
  "Deja que otro jugador lea en voz alta tu último mensaje recibido.",
  "Bebe un vaso de agua de un solo trago.",
  "Envía un mensaje de voz cantando una canción elegida por el grupo.",
  "Deja que otro jugador cambie tu estado en WhatsApp o redes sociales.",
  "Haz un dibujo ridículo en tu cara con un marcador lavable.",
  "Envía un mensaje de voz a alguien hablando pendejadas.",
  "Haz una llamada a un amigo y confiesa un amor platónico falso.",
];
